/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = ['abilities', 'createdAt', 'expiresAt', 'hash', 'id', 'lastUsedAt', 'name', 'tokenableId', 'type', 'updatedAt'] as const
  $columns = AuthAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class CheckInSchema extends BaseModel {
  static $columns = ['confidenceWeight', 'courtGroupId', 'courtId', 'createdAt', 'id', 'latitude', 'longitude', 'racketsWaiting', 'source', 'status', 'userId'] as const
  $columns = CheckInSchema.$columns
  @column()
  declare confidenceWeight: string
  @column()
  declare courtGroupId: number | null
  @column()
  declare courtId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare latitude: string
  @column()
  declare longitude: string
  @column()
  declare racketsWaiting: number | null
  @column()
  declare source: string
  @column()
  declare status: string
  @column()
  declare userId: number
}

export class CourtGroupSchema extends BaseModel {
  static $columns = ['courtCount', 'courtId', 'createdAt', 'id', 'name', 'notes', 'sessionTimeMinutes', 'updatedAt'] as const
  $columns = CourtGroupSchema.$columns
  @column()
  declare courtCount: number
  @column()
  declare courtId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare notes: string | null
  @column()
  declare sessionTimeMinutes: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class CourtSchema extends BaseModel {
  static $columns = ['address', 'createdAt', 'id', 'isPriority', 'latitude', 'longitude', 'name', 'photoUrl', 'slug', 'totalCourtCount', 'updatedAt'] as const
  $columns = CourtSchema.$columns
  @column()
  declare address: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isPriority: boolean
  @column()
  declare latitude: string
  @column()
  declare longitude: string
  @column()
  declare name: string
  @column()
  declare photoUrl: string | null
  @column()
  declare slug: string
  @column()
  declare totalCourtCount: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class DenyListSchema extends BaseModel {
  static $columns = ['createdAt', 'expiresAt', 'id', 'reason', 'type', 'value'] as const
  $columns = DenyListSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare reason: string | null
  @column()
  declare type: string
  @column()
  declare value: string
}

export class PresenceSchema extends BaseModel {
  static $columns = ['courtId', 'enteredAt', 'etaMinutes', 'id', 'isHeadingHere', 'lastHeartbeatAt', 'userId'] as const
  $columns = PresenceSchema.$columns
  @column()
  declare courtId: number
  @column.dateTime()
  declare enteredAt: DateTime
  @column()
  declare etaMinutes: number | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isHeadingHere: boolean
  @column.dateTime()
  declare lastHeartbeatAt: DateTime
  @column()
  declare userId: number
}

export class RateLimitSchema extends BaseModel {
  static $columns = ['expire', 'key', 'points'] as const
  $columns = RateLimitSchema.$columns
  @column()
  declare expire: bigint | number | null
  @column({ isPrimary: true })
  declare key: string
  @column()
  declare points: number
}

export class UserSchema extends BaseModel {
  static $columns = ['avatarUrl', 'bio', 'createdAt', 'email', 'fullName', 'hideName', 'homeCourtIds', 'id', 'isAmbassador', 'isSuperAdmin', 'password', 'phone', 'playStyle', 'preferredTimes', 'profileCompletedAt', 'showToOthers', 'skillLevel', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column()
  declare avatarUrl: string | null
  @column()
  declare bio: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column()
  declare hideName: boolean
  @column()
  declare homeCourtIds: any | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isAmbassador: boolean
  @column()
  declare isSuperAdmin: boolean
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare phone: string | null
  @column()
  declare playStyle: any | null
  @column()
  declare preferredTimes: any | null
  @column.dateTime()
  declare profileCompletedAt: DateTime | null
  @column()
  declare showToOthers: boolean
  @column()
  declare skillLevel: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class WaitlistEntrySchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'id', 'referrer', 'source', 'updatedAt'] as const
  $columns = WaitlistEntrySchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare referrer: string | null
  @column()
  declare source: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
