/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = ['abilities', 'createdAt', 'expiresAt', 'hash', 'id', 'lastUsedAt', 'name', 'tokenableId', 'type', 'updatedAt'] as const
  $columns = AuthAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class CheckInSchema extends BaseModel {
  static $columns = ['confidenceWeight', 'courtGroupId', 'courtId', 'createdAt', 'id', 'latitude', 'longitude', 'racketsWaiting', 'status', 'userId'] as const
  $columns = CheckInSchema.$columns
  @column()
  declare confidenceWeight: string
  @column()
  declare courtGroupId: number | null
  @column()
  declare courtId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare latitude: string
  @column()
  declare longitude: string
  @column()
  declare racketsWaiting: number | null
  @column()
  declare status: string
  @column()
  declare userId: number
}

export class CourtGroupSchema extends BaseModel {
  static $columns = ['courtCount', 'courtId', 'createdAt', 'id', 'name', 'notes', 'sessionTimeMinutes', 'updatedAt'] as const
  $columns = CourtGroupSchema.$columns
  @column()
  declare courtCount: number
  @column()
  declare courtId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare notes: string | null
  @column()
  declare sessionTimeMinutes: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class CourtSchema extends BaseModel {
  static $columns = ['address', 'createdAt', 'id', 'isPriority', 'latitude', 'longitude', 'name', 'photoUrl', 'slug', 'totalCourtCount', 'updatedAt'] as const
  $columns = CourtSchema.$columns
  @column()
  declare address: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isPriority: boolean
  @column()
  declare latitude: string
  @column()
  declare longitude: string
  @column()
  declare name: string
  @column()
  declare photoUrl: string | null
  @column()
  declare slug: string
  @column()
  declare totalCourtCount: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'fullName', 'id', 'isAmbassador', 'password', 'phone', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isAmbassador: boolean
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare phone: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
